#lang sicp
(define (make-point x y)
  (cons x y))
(define (make-segment a b)
  (cons a b))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (start-segment seg)
  (car seg))
(define (end-segment seg)
  (cdr seg))
(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")")
  (newline))
(define (midpoint-segment seg)
  (define start (start-segment seg))
  (define end (end-segment seg))
  (make-point (/ (+ (x-point start) (x-point end)) 2.0)
              (/ (+ (y-point start) (y-point end)) 2.0)))
(define point1a (make-point 1 2))
(define point1b (make-point 2 -6))
(define point2a (make-point 4 2))
(define point2b (make-point 10 -100))
(define seg1 (make-segment point1a point1b))
(define seg2 (make-segment point2a point2b))
(print-point (midpoint-segment seg1))